- hosts: arn
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 10443
  tasks:
    - name: Granite 1 
      fortinet.fortios.fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP1"
          type: "ipmask"
          subnet: "54.241.160.4/32"
          allow_routing: "enable"

    - name: Granite 2
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP2"
          type: "ipmask"
          subnet: "54.241.163.234/32"
          allow_routing: "enable"

    - name: Granite 3
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP3"
          type: "ipmask"
          subnet: "54.67.107.54/32"
          allow_routing: "enable"

    - name: Granite 4
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP4"
          type: "ipmask"
          subnet: "54.67.113.163/32"
          allow_routing: "enable"

    - name: Granite 5
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP5"
          type: "ipmask"
          subnet: "54.219.101.213/32"
          allow_routing: "enable"

    - name: Granite 6
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP6"
          type: "ipmask"
          subnet: "52.52.249.241/32"
          allow_routing: "enable"

    - name: Granite 7
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP7"
          type: "ipmask"
          subnet: "52.53.96.55/32"
          allow_routing: "enable"

    - name: Granite 8
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP8"
          type: "ipmask"
          subnet: "13.52.69.0/32"
          allow_routing: "enable"

    - name: Granite 9
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP9"
          type: "ipmask"
          subnet: "54.241.91.173/32"
          allow_routing: "enable"

    - name: Granite 10
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP10"
          type: "ipmask"
          subnet: "52.9.223.41/32"
          allow_routing: "enable"

    - name: Granite 11
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP11"
          type: "ipmask"
          subnet: "52.9.225.203/32"
          allow_routing: "enable"

    - name: Granite 12
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP12"
          type: "ipmask"
          subnet: "13.56.185.145/32"
          allow_routing: "enable"

    - name: Granite 13
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom-IP13"
          type: "ipmask"
          subnet: "13.57.121.193/32"
          allow_routing: "enable"  

    - name: Granite gdms
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-gdms"
          type: "fqdn"
          fqdn: "*.gdms.cloud"
          allow_routing: "enable" 

    - name: Granite granitevoip
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-granitevoip"
          type: "fqdn"
          fqdn: "*.granitevoip.com"
          allow_routing: "enable"   

    - name: Granite metaswitch
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-metaswitch"
          type: "fqdn"
          fqdn: "*.metaswitch.com"
          allow_routing: "enable"

    - name: Granite obitalk
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-obitalk"
          type: "fqdn"
          fqdn: "*.obitalk.com"
          allow_routing: "enable"

    - name: Granite polycom
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-polycom"
          type: "fqdn"
          fqdn: "*.polycom.com"
          allow_routing: "enable"

    - name: Granite provisioning
      fortios_firewall_address:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        firewall_address:
          name: "granite-provisioning"
          type: "fqdn"
          fqdn: "*.connecting.net"
          allow_routing: "enable"
