- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: addrgrp_High Touch 0 local
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "High Touch 0_local"
          member:
            -
              name: "internal"

    - name: addrgrp_RSSSHOII local
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "RSSS HO II_local"
          member:
            -
              name: "internal"

    - name: addrgrp_ddc local
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "ddc1-fw01_local"
          member:
            -
              name: "internal"
      when:
        - ddc_hosted == "yes"

    - name: addrgrp_High Touch 0 remote
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "High Touch 0_remote"
          allow_routing: "enable"
          member:
            -
              name: "HighTouch0"  

    - name: addrgrp_RSSSHOII remote
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "RSSS HO II_remote"
          allow_routing: "enable"
          member:
            -
              name: "RSSSHOII"   

    - name: addrgrp_ddc remote
      fortios_firewall_addrgrp:
        state: "present"
        access_token: "{{ fortios_access_token}}"
        firewall_addrgrp:
          name: "ddc1-fw01_remote"
          allow_routing: "enable"
          member:
            -
              name: "ddc1-fw01"
      when:
        - ddc_hosted == "yes"                            