- hosts: prod
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 10443
  tasks:
    - name: set fm.hightouchinc.com
      fortios_system_central_management:
        access_token: "{{ fortios_access_token }}"
        system_central_management:
          type: "fortimanager"
          fmg: "fm.hightouchinc.com"
          interface_select_method: "sdwan"

