- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: Register Allowed URLs from CSV file
      read_csv:
        path: ./files/hunter_allowed.csv
      register: allowed

    - name: Add Allowed URLs to Custom1 Web Rating Overrides
      fortios_webfilter_ftgd_local_rating:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        webfilter_ftgd_local_rating:
          rating: "140"
          status: "enable"
          url: "{{ item.url }}"
      loop: "{{ allowed.list }}"
      when: item.url is defined

    - name: Register Blocked URLs from CSV file
      read_csv:
        path: ./files/hunter_blocked.csv
      register: blocked

    - name: Add Blocked URLs to Custom1 Web Rating Overrides
      fortios_webfilter_ftgd_local_rating:
        vdom: "{{ vdom }}"
        state: present
        access_token: "{{ fortios_access_token }}"
        webfilter_ftgd_local_rating:
          rating: "141"
          status: "enable"
          url: "{{ item.url }}"
      loop: "{{ blocked.list }}"
      when: item.url is defined
