- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - global_vars.yml
  vars:
  tasks:
    - name: set WAN 
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface: 
          vdom: "{{ vdom }}"
          name: "wan"
          mode: "dhcp"
          allowaccess: "https,http,fgfm"
          dns_server_override: "disable"
      when: 
        - wan_dhcp == "yes"

    - name: set lan 
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface: 
          vdom: "{{ vdom }}"
          name: "internal"
          ip: "{{ lan }}"
          allowaccess: "https,http,fgfm,ssh,ping,fabric"
          device_identification: "enable"
          dns_server_override: "disable"
      when: 
        - wifi == "no"

    - name: set lan/wifi
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface: 
          vdom: "{{ vdom }}"
          name: "internal"
          ip: "{{ lan }}"
          allowaccess: "https,http,fgfm,ssh,ping,fabric"
          device_identification: "enable"
          dns_server_override: "disable"
          member:
          -
            interface_name: "lan"
      when: 
        - wifi == "yes" 

    - name: wifi
      fortios_wireless_controller_vap:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        wireless_controller_vap:
          name: "wifi"
          ssid: "{{customer}}{{store_num}}-rto"
          passphrase: "{{customer}}customersare1"
          schedule:
          - name: "always"
      when:
        - wifi == "yes"

    - name: set lan/wifi
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface: 
          vdom: "{{ vdom }}"
          name: "wifi"
          ip: "172.16.31.1/24"
          allowaccess: "https,http,fgfm,ssh,ping,fabric"
          device_identification: "enable"
          dns_server_override: "disable"
      when: 
        - wifi == "yes" 

   # - name: DHCP 
   #   fortios_system_dhcp_server:
   #     vdom: "{{ vdom }}"
   #     state: "present"
   #     access_token: "{{ fortios_access_token }}"
   #     system_dhcp_server:
   #       id: "1"
   #       default_gateway: "{{ lan_gw }}"
   #       netmask: "255.255.255.192"
   #       interface: "internal"
   #       ip_range:
   #       -
   #         start_ip: "{{ startip }}"
   #         end_ip: "{{ endip }}"

    - name: remove wan rule
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        firewall_policy:
          policyid: "1"

    - name: remove wan wifi rule
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        firewall_policy:
          policyid: "2"