- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - global_vars.yml
  vars:
  tasks:
    #removal of Default Policies
    - name: Delete Default Policy 1
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        firewall_policy:
          policyid: "1"

    - name: Delete Default Policy 2
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        firewall_policy:
          policyid: "2"
    #remove DHCP Servers 
    - name: Delete Default lan DHCP
      fortios_system_dhcp_server:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        system_dhcp_server:
          id : "1"