- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:

    - name: StoreHosted VPNp2 Main
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "{{ customer }}{{ storeid }}-rto_1"
          phase1name: "{{ customer }}{{ storeid }}-rto_1"
          proposal: "aes256-sha1"
          psf: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "{{ customer }}{{ storeid }}_local"
          dst_name: "{{ customer }}{{ storeid }}_remote"
          keylifeseconds: "28800"

    - name: StoreHosted VPNp2 backup
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "{{ customer }}{{ storeid }}-rto_2"
          phase1name: "{{ customer }}{{ storeid }}-rto_2"
          proposal: "aes256-sha1"
          psf: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "{{ customer }}{{ storeid }}_local"
          dst_name: "{{ customer }}{{ storeid }}_remote"
          keylifeseconds: "28800"