- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: vpn_High touch 0_1 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "High Touch 0_1"
          phase1name: "High Touch 0_1"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "High Touch 0_local"
          dst_name: "High Touch 0_remote"
          keylifeseconds: "28800"

    - name: vpn_High touch 0_2 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "High Touch 0_2"
          phase1name: "High Touch 0_2"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "High Touch 0_local"
          dst_name: "High Touch 0_remote"
          keylifeseconds: "28800"

    - name: vpn_RSSSHOII_1 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "RSSSHOII_1"
          phase1name: "RSSSHOII_1"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "RSSS HO II_local"
          dst_name: "RSSS HO II_remote"
          keylifeseconds: "28800"

    - name: vpn_RSSSHOII_2 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "RSSSHOII_2"
          phase1name: "RSSSHOII_2"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "RSSS HO II_local"
          dst_name: "RSSS HO II_remote"
          keylifeseconds: "28800"

    - name: vpn_ddc1-fw01_1 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "ddc1-fw01_1"
          phase1name: "ddc1-fw01_1"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "ddc1-fw01_local"
          dst_name: "ddc1-fw01_remote"
          keylifeseconds: "28800"
      when:
        - ddc_hosted == "yes"

    - name: vpn_ddc1-fw01_2 p2
      fortios_vpn_ipsec_phase2_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        vpn_ipsec_phase2_interface:
          name: "ddc1-fw01_2"
          phase1name: "ddc1-fw01_2"
          proposal: "aes256-sha1"
          pfs: "disable"
          keepalive: "enable"
          src_addr_type: "name"
          dst_addr_type: "name"
          src_name: "ddc1-fw01_local"
          dst_name: "ddc1-fw01_remote"
          keylifeseconds: "28800"
      when:
        - ddc_hosted == "yes"