- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - ../../vars.yml
  vars:
  tasks:
    - name: Delete Default Firewall Policy
      fortios_firewall_policy:
        access_token: "{{ fortios_access_token }}"
        state: "absent"
        firewall_policy:
          policyid: "1"

    - name: Change wan2 for Extender
      fortios_system_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface:
          name: "wan2"
          role: "undefined"
          ip: "10.254.254.1/30"
          allowaccess: "fabric"

    - name: Set DCHP for wan2
      fortios_system_dhcp_server:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_dhcp_server:
          id: "0"
          default_gateway: "10.254.254.1"
          netmask: "255.255.255.252"
          interface: "wan2"
          ip_range: 
          -
            id: "0"
            start_ip: "10.254.254.2"
            end_ip: "10.254.254.2"
            
    - name: Set Extender Interface
      fortios_system_interface:
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface:
          vdom: "{{ vdom }}"
          name: "Extender"
          type: "fext-wan"
          mode: "dhcp"
          role: "wan"
          dns_server_override: "disable"