- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: set lan 
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_interface: 
          vdom: "{{ vdom }}"
          name: "internal"
          ip: "{{ lan }}"
          allowaccess: "https,http,fgfm,ssh,ping,fabric"
          device_identification: "enable"
          dns_server_override: "disable"

    - name: DHCP 
      fortios_system_dhcp_server:
        vdom: "{{ vdom }}"
        state: "present"
        access_token: "{{ fortios_access_token }}"
        system_dhcp_server:
          id: "1"
          default_gateway: "{{ lan_gw }}"
          netmask: "255.255.255.0"
          interface: "internal"
          ip_range:
          -
            start_ip: "{{ startip }}"
            end_ip: "{{ endip }}"