- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
  tasks:
    - name: Set System Settings
      fortios_system_global:
        access_token: "{{ fortios_access_token }}"
        system_global: 
          hostname: "{{customer}}{{store_num}}-rto"
          admin_port: "8080"
          admin_sport: "10443"
          admintimeout: "30"